---
short: 2
int: 4
long: 8
long long: 8

double: 8
# Current SL implementation supports only parameters not wider than 8B thus support for
# (normally 16B wide) long double is very limited
long double: 8

wchar_t: 2
intmax_t: 8
size_t: 8
ptrdiff_t: 8
void*: 8
